
import { Product, RawMaterial } from './types';

export const PRODUCTS: Product[] = [
  // Poultry Feed
  { code: '511', name: 'ব্রয়লার স্টার্টার', bagSize: 50, protein: '22.00%', category: 'Poultry' },
  { code: '512', name: 'ব্রয়লার গ্রোয়ার', bagSize: 50, protein: '21.00%', category: 'Poultry' },
  { code: '513', name: 'ব্রয়লার ফিনিশার', bagSize: 50, protein: '21.00%', category: 'Poultry' },
  { code: '514', name: 'লেয়ার স্টার্টার', bagSize: 50, protein: '19.50%', category: 'Poultry' },
  { code: '515', name: 'লেয়ার গ্রোয়ার', bagSize: 50, protein: '19.50%', category: 'Poultry' },
  { code: '516', name: 'লেয়ার লেয়ার-১', bagSize: 50, protein: '18.00%', category: 'Poultry' },
  { code: '517', name: 'সোনালী স্টার্টার', bagSize: 50, protein: '22.00%', category: 'Poultry' },
  { code: '518', name: 'সোনালী গ্রোয়ার', bagSize: 50, protein: '21.00%', category: 'Poultry' },
  { code: '519', name: 'ব্রয়লার হাউজ ফিড (ক্রাম্বল)', bagSize: 25, protein: '16.00%', category: 'Poultry' },
  { code: '510', name: 'ব্রয়লার হাউজ ফিড', bagSize: 25, protein: '16.00%', category: 'Poultry' },
  
  // Fish/Shrimp Feed
  { code: '610', name: 'নার্সারী/হ্যাচারী (পাউডার)', bagSize: 10, protein: '38.00%', category: 'Fish' },
  { code: '611', name: 'তেলাপিয়া/পাঙ্গাস স্টার্টার', bagSize: 20, protein: '28.00%', category: 'Fish' },
  { code: '612', name: 'তেলাপিয়া/পাঙ্গাস গ্রোয়ার', bagSize: 20, protein: '26.00%', category: 'Fish' },
  { code: '613', name: 'তেলাপিয়া/পাঙ্গাস ফিনিশার', bagSize: 20, protein: '24.00%', category: 'Fish' },
  { code: '614', name: 'মিশ্র কার্প স্টার্টার', bagSize: 20, protein: '25.00%', category: 'Fish' },
  { code: '615', name: 'মিশ্র কার্প গ্রোয়ার', bagSize: 20, protein: '23.00%', category: 'Fish' },
  { code: '616', name: 'মিশ্র কার্প ফিনিশার', bagSize: 20, protein: '21.00%', category: 'Fish' },
  { code: '617', name: 'মিশ্র কার্প গ্রোয়ার (ইকো)', bagSize: 20, protein: '20.00%', category: 'Fish' },
  { code: '618', name: 'তেলাপিয়া/পাঙ্গাস গ্রোয়ার (ডুবন্ত)', bagSize: 25, protein: '26.00%', category: 'Fish' },
  { code: '619', name: 'মিশ্র কার্প গ্রোয়ার (ডুবন্ত)', bagSize: 25, protein: '23.00%', category: 'Fish' },
  { code: '620', name: 'গলদা/বাগদা গ্রোয়ার গোল্ড (ডুবন্ত)', bagSize: 20, protein: '32.00%', category: 'Fish' },
  { code: '621', name: 'গলদা/বাগদা গ্রোয়ার গোল্ড (ডুবন্ত)', bagSize: 25, protein: '29.00%', category: 'Fish' },

  // Cattle Feed
  { code: '710', name: 'ক্যাটল মিল্ক প্রিমিয়াম', bagSize: 25, protein: '18.00%', category: 'Cattle' },
  { code: '711', name: 'ক্যাটল বীফ প্রিমিয়াম', bagSize: 25, protein: '18.00%', category: 'Cattle' },
  { code: '712', name: 'ক্যাটল মিল্ক ক্লাসিক', bagSize: 25, protein: '17.00%', category: 'Cattle' },
  { code: '713', name: 'ক্যাটল বীফ ক্লাসিক', bagSize: 25, protein: '17.00%', category: 'Cattle' },
  { code: '714', name: 'ক্যাটল মিল্ক পপুলার', bagSize: 25, protein: '16.00%', category: 'Cattle' },
  { code: '715', name: 'ক্যাটল বীফ পপুলার', bagSize: 25, protein: '16.00%', category: 'Cattle' },
  { code: '716', name: 'ক্যাটল বুস্টার সোফিডমেন্ট (ম্যাশ)', bagSize: 25, protein: '17.00%', category: 'Cattle' },
];

export const RAW_MATERIALS: RawMaterial[] = [
  // Existing materials
  { id: 'rm1', name: 'সয়াবিন মিল (Soybean Meal)', unit: 'kg' },
  { id: 'rm2', name: 'রেপসীড (Rapeseed)', unit: 'kg' },
  { id: 'rm3', name: 'ভুট্টা (Maize)', unit: 'kg' },
  { id: 'rm4', name: 'রাইচ পালিশ (Rice Polish)', unit: 'kg' },
  { id: 'rm5', name: 'ডিওআরবি (DORB)', unit: 'kg' },
  { id: 'rm6', name: 'কাটিং পালিশ/ডায়া পালিশ', unit: 'kg' },
  { id: 'rm7', name: 'ফিস মিল (Fish Meal)', unit: 'kg' },
  { id: 'rm8', name: 'সিজিএম (CGM)', unit: 'kg' },
  { id: 'rm9', name: 'ডিডিজিএস (DDGS)', unit: 'kg' },
  { id: 'rm10', name: 'ড্রাই ফিস/শুটকি', unit: 'kg' },
  { id: 'rm11', name: 'বেকারী মিল', unit: 'kg' },
  { id: 'rm12', name: 'আটা/ময়দা', unit: 'kg' },
  { id: 'rm13', name: 'লাইম স্টোন ২/৩', unit: 'kg' },
  { id: 'rm14', name: 'লাইম স্টোন (পাউডার)', unit: 'kg' },
  { id: 'rm15', name: 'লবন (Salt)', unit: 'kg' },
  { id: 'rm16', name: 'ফিস অয়য়েল', unit: 'kg' },
  { id: 'rm17', name: 'সয়াবিন/পাম অয়য়েল', unit: 'kg' },
  { id: 'rm18', name: 'পিলেট বাইন্ডার', unit: 'kg' },
  { id: 'rm19', name: 'টক্সিন বাইন্ডার', unit: 'kg' },
  { id: 'rm20', name: 'হলুদ (Turmeric)', unit: 'kg' },
  { id: 'rm21', name: 'ফিড কালার', unit: 'kg' },
  { id: 'rm22', name: 'কোরিয়ান কর্ণ পাউডার', unit: 'kg' },
  { id: 'rm23', name: 'গম (Wheat)', unit: 'kg' },
  { id: 'rm24', name: 'মোটা ভূষি (Bold Bran)', unit: 'kg' },
  { id: 'rm25', name: 'চিকন ভূষি (Slim Bran)', unit: 'kg' },
  { id: 'rm26', name: 'বার্লি (Barley)', unit: 'kg' },
  { id: 'rm27', name: 'দেশি কুড়া (Local Polish)', unit: 'kg' },
  { id: 'rm28', name: 'নালী/চিটাগুড় (Molasses)', unit: 'kg' },
  
  // New items from PDF (Excluding duplicates)
  { id: 'rm29', name: 'গমের ভুসি (Wheat Bran)', unit: 'kg' },
  { id: 'rm30', name: 'চালের কুড়া (Rice Bran)', unit: 'kg' },
  { id: 'rm31', name: 'ফুল ফ্যাট সয়াবিন (Full Fat Soybean)', unit: 'kg' },
  { id: 'rm32', name: 'মিট ও বোন মিল (Meat & Bone Meal)', unit: 'kg' },
  { id: 'rm33', name: 'পোল্ট্রি বাই প্রোডাক্ট মিল (Poultry By-Product)', unit: 'kg' },
  { id: 'rm34', name: 'চুনাপাথর গুঁড়া (Limestone Powder)', unit: 'kg' },
  { id: 'rm35', name: 'ডাই ক্যালসিয়াম ফসফেট (DCP)', unit: 'kg' },
  { id: 'rm36', name: 'মনো ক্যালসিয়াম ফসফেট (MCP)', unit: 'kg' },
  { id: 'rm37', name: 'জিঙ্ক অক্সাইড (Zinc Oxide)', unit: 'kg' },
  { id: 'rm38', name: 'ভিটামিন এ (Vitamin A)', unit: 'kg' },
  { id: 'rm39', name: 'ভিটামিন ডি৩ (Vitamin D3)', unit: 'kg' },
  { id: 'rm40', name: 'ভিটামিন ই (Vitamin E)', unit: 'kg' },
  { id: 'rm41', name: 'ভিটামিন বি কমপ্লেক্স (Vitamin B Complex)', unit: 'kg' },
  { id: 'rm42', name: 'লাইসিন (Lysine)', unit: 'kg' },
  { id: 'rm43', name: 'মিথিওনিন (Methionine)', unit: 'kg' },
  { id: 'rm44', name: 'ফাইটেজ (Phytase)', unit: 'kg' },
  { id: 'rm45', name: 'জাইলানেজ (Xylanase)', unit: 'kg' },
  { id: 'rm46', name: 'প্রোবায়োটিক (Probiotics)', unit: 'kg' },
  { id: 'rm47', name: 'প্রিবায়োটিক (Prebiotics)', unit: 'kg' },
  { id: 'rm48', name: 'সয়াবিন তেল (Soybean Oil)', unit: 'kg' },
  { id: 'rm49', name: 'ইথক্সিকুইন (Ethoxyquin)', unit: 'kg' },
  { id: 'rm50', name: 'BHT (Butylated Hydroxytoluene)', unit: 'kg' },
  { id: 'rm51', name: 'স্পাইরুলিনা (Spirulina)', unit: 'kg' },
  { id: 'rm52', name: 'অ্যাসটাক্সানথিন (Astaxanthin)', unit: 'kg' },
];
